### ISSUE TITLE
LD2410C

### ISSUE THREAD

**Issue by arizodude** [rain931215/ESPHome-LD2410#11]
Does the code also work with the 2410C

**Comment by bartjanisse** [comment]
Same question for me, is the code working with a LD2410C. I hope so

Thanks for all the good work

Did test it and it seems to work sofar

**Comment by alexruffell** [comment]
As far as I know the B and C versions are identical. The only difference is the form factor that makes the C version breadboard friendly. Both have a BT radio as well. I have both and can interchange either one with the native LD2410 integration in HA. I found this while looking for ways to move the configuration of the sensor outside of the hardcoded yaml and into the settings on the device page in HA but I would rather not install custom components to get that ability...

**Comment by arizodude** [comment]
Okay, thank you ... I will give it a try with the LD2410C.

**Comment by tieppm** [comment]
i am using with LD2410C. it works great

**Comment by arizodude** [comment]
I tried it an can confirm it works just fine with the LD2410C. 

Thank you all!

**Comment by arizodude** [comment]
I will close this now
